[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "packeteer"
version = "0.10.0"
requires-python = ">=3.10"
description = "Pure-Python library for building, parsing, and sanitising raw network packets"
authors = [ { name = "Adam Jonsson", email = "adam.jonsson@live.se"} ]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Telecommunications Industry",
    "Topic :: System :: Networking",
    "Topic :: System :: Networking :: Monitoring",
    "Topic :: Security",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13" ]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["packeteer*"]

[tool.setuptools.package-data]
"packeteer.generate" = ["default_payload.txt", "stream.ini.template"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["src/tests"]

[project.scripts]
packeteer = "packeteer.__main__:main"

[project.urls]
Repository = "https://github.com/adamkjonsson/packeteer.git"
Changelog = "https://github.com/adamkjonsson/packeteer/blob/main/CHANGELOG.md"
Issues = "https://github.com/adamkjonsson/packeteer/issues"